// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/blog.tsx";
import * as $1 from "./routes/blog/[title].tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/EmploymentHistory.tsx";
import * as $$1 from "./islands/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/blog.tsx": $0,
    "./routes/blog/[title].tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/EmploymentHistory.tsx": $$0,
    "./islands/NavBar.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
